AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Remove um determinado cliente da fila (redis) e salva o fim da fila no
  transacional (mysq)
Resources:
  removeclientqueue:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: >-
        Remove um determinado cliente da fila (redis) e salva o fim da fila no
        transacional (mysq)
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/client/{id}'
            Method: DELETE
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Layers:
        - ''
